name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          config_timezone: Asia/Seoul
          
          # Base content(사용자 정보) 표시하지 않음
          base: ""
          
          # isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # plugin_languages
          plugin_languages: yes
          plugin_languages_skipped: parkgang/parkgang.github.io, parkgang/JSP-Web-Wordbook
          
          # plugin_stackoverflow
          # plugin_stackoverflow: yes
          # plugin_stackoverflow_user: 14471375
          # plugin_stackoverflow_sections: ""
